INSERT INTO demo.genre (name, code) VALUES ('инди-рок', 'indie_rock');
INSERT INTO demo.genre (name, code) VALUES ('мидвест-эмо', 'midwest');
INSERT INTO demo.genre (name, code) VALUES ('поп-панк', 'pop_punk');
INSERT INTO demo.genre (name, code) VALUES ('инди-поп', 'indie_pop');
INSERT INTO demo.genre (name, code) VALUES ('дрим-поп', 'dream_pop');
INSERT INTO demo.genre (name, code) VALUES ('эмо', 'emo');
INSERT INTO demo.genre (name, code) VALUES ('пост-панк', 'post_punk');
INSERT INTO demo.genre (name, code) VALUES ('альтернативный рок', 'alternative');
INSERT INTO demo.genre (name, code) VALUES ('скримо', 'screamo');
INSERT INTO demo.genre (name, code) VALUES ('скрамз', 'skramz');
INSERT INTO demo.genre (name, code) VALUES ('художественная декламация', 'spoken_word');
INSERT INTO demo.genre (name, code) VALUES ('математический рок', 'math_rock');